feat: merged main branch.
Co-authored-by: JackAltman
<82563979+JackA1ltman@users.noreply.github.com>

diff --git a/.github/workflows/build_kernel_arch_template.yml b/.github/workflows/build_kernel_arch_template.yml
--- a/.github/workflows/build_kernel_arch_template.yml
+++ b/.github/workflows/build_kernel_arch_template.yml
@@ -593,6 +593,15 @@ jobs:
           patch -p1 < susfs_upgrade_to_1510_${{ env.KERNEL_VERSION }}.patch || true
           echo "Detected no-kprobe hook, use no-kprobe patch to update 1.5.10."
 
+          # Upgrade 1.5.11
+          if grep -q "susfs_reorder_mnt_id" "drivers/kernelsu/core_hook.c"; then
+            cp /tmp/Patches/Patch/susfs_upgrade_to_1511_${{ env.KERNEL_VERSION }}.patch ./
+            patch -p1 < susfs_upgrade_to_1511_${{ env.KERNEL_VERSION }}.patch || true
+            echo "Detected no-kprobe hook, use no-kprobe patch to update 1.5.11"
+          else
+            echo "Your kernelsu fork cannot supported SuSFS 1.5.11. Skipped."
+          fi
+
           # Extra SUSFS Patch
           # cp NonGKI_Kernel_Patches/[patch_folder]/[patch_file].patch ./
 
